### ISSUE TITLE
Amazing work. I have a question related to the ROPE embedding.

### ISSUE THREAD

**Issue by shamanez** [nverma1/merging-text-transformers#1]
By any chance did you experiment with Transformer Models that have ROPE embeddings?  Thanks a lot.

**Comment by nverma1** [comment]
Hi, thanks for your question!

We did not experiment with RoPE as we considered only positional embeddings (that get merged with the rest of the residual merges), but I imagine that our method can still apply, especially as RoPE is parameterless.

**Comment by shamanez** [comment]
Thanks for the clarification. I'll try to apply your method to an LLM with RoPE embeddings and let you know.

**Comment by daidaiershidi** [comment]
> Thanks for the clarification. I'll try to apply your method to an LLM with RoPE embeddings and let you  

Hi, I'm also trying to apply this method to Llama. May I ask if P_{MHA}^T can be directly used for rotary_emb?  Thanks a lot.
