### ISSUE TITLE
Applying fusion to a ViT from a different package

### ISSUE THREAD

**Issue by idankinderman** [nverma1/merging-text-transformers#2]
Hi,

Let's say I want to apply your fusion method to a PyTorch-based ViT implemented in a package that isn't Hugging Face. Specifically, I want to merge ViTs from the open_clip package (https://github.com/mlfoundations/open_clip). What changes do I need to make in your code to make it work?

Thank you for your great work!

Edan

**Comment by nverma1** [comment]
Hi Edan,

Thank you for interest! 
You will probably need to write your own model file, and define all points you would like to collect features in a Graph object. We prep our models in the `prepare_bert` method in the utils file - you can change this to reflect loading your models. Computing matching in [matching_functions.py](https://github.com/nverma1/merging-text-transformers/blob/main/matching_functions.py), and computing correlations in [metric_calculators.py](https://github.com/nverma1/merging-text-transformers/blob/main/metric_calculators.py). You also may have to check the `apply_transformations_custom` method in [model_merger.py](https://github.com/nverma1/merging-text-transformers/blob/main/model_merger.py) to ensure names for pytorch layers are named appropriately in your model.
