### ISSUE TITLE
Why LN doesn't require any P^{T}

### ISSUE THREAD

**Issue by daidaiershidi** [nverma1/merging-text-transformers#3]
Thank you for bringing such interesting work. I'm curious to know why LN doesn't require any P^{T} (unmerge.weight)?

**Comment by nverma1** [comment]
Hello,

Thanks for your interest in the work!
LN does require permutations, but the permutation is always the same as the layer it follows. The post-layer features are in the same order after the layer as well as after the LN, as LN is just a 1D transform, whereas the layer it follows is a 2D transform. 

The code that handles LN is all in apply_transformations_custom in the model_merger.py file https://github.com/nverma1/merging-text-transformers/blob/main/model_merger.py#L632. I hope this helps!

**Comment by daidaiershidi** [comment]
Thank you very much for being willing to answer my questions.

Throughout the entire process, multiplying the parameters (whether it's linear.weight or norm_layer.weight) on the right by P represents the aligned feature space (this will take effect after X enters that layer), while multiplying the parameters on the left represents the restoration to the original feature space, and they will be multiplied by the parameters W in the original space.
 
For example, given W_l, P_l, and P_l^T in the l-th layer, new_W_l = P_l^T @ W_l @ P_l. 

When X is the original input in 0-th layer, X@W_l produces the original feature space, and X@W_l@P_l projects from the original feature space to the aligned feature space. 

However, in deep networks, because X is the output of the previous layer, it similarly comes from the aligned feature space, and W can only take effect in the original feature space. Therefore, for W_l to be usable, before multiplying X by W_l, the output of the previous layer needs to be restored to the feature space where W is effective, so we need to multiply it by P^T on the left. 

What I'm puzzled about is why LN can be directly used on features from the aligned feature space.

**Comment by nverma1** [comment]
LN also gets permuted by the same matrix that creates the aligned feature space. After computing statistics (not order dependent), LN applies to each neuron individually. The order that the neurons are passed to LN is dictated by the P_I in your example, and then LN also receives a permutation from P_I as well so that the 1D weights and 1D bias terms are applied in the correct order. Because LN is 1D, however, it does not warrant an additional alignment computation as does full weight matrices. I hope this answers your question

**Comment by daidaiershidi** [comment]
I am a beginner in this field, and I appreciate your explanation, which has been immensely helpful to me. I understand the description in your paper now, and the fundamental reason, as I grasp it, lies in the fact that LN (Layer Normalization) operates more like dot product, rather than matrix multiplication.
