### ISSUE TITLE
Download Link for BookCorpus data

### ISSUE THREAD

**Issue by zelaki** [nverma1/merging-text-transformers#4]
Hello and thank you for the interesting work!
I want to try and replicate some of your experiments but I can't seem to find a link to the BookCorpus dataset that has a similar structure to what you describe in the download script (BOOKSROOT/{genre}/{book}.txt).
Could you provide the URL used to download the dataset?
Thanks in advance,
Thodoris

**Comment by nverma1** [comment]
Hi Thodoris, 
The BookCorpus is no longer available at the original download link. We used a local copy that was acquired some time ago. Many people have tried to replicate the original crawl, and a decent copy can be downloaded from Huggingface: [https://huggingface.co/datasets/bookcorpus/bookcorpus](https://huggingface.co/datasets/bookcorpus/bookcorpus). This should suffice as the example forward passes are only a subset of the corpus. 
-Neha
